// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadGame() {
  return window['go']['main']['App']['DownloadGame']();
}

export function GetGPUs() {
  return window['go']['main']['App']['GetGPUs']();
}

export function GetGameOpts() {
  return window['go']['main']['App']['GetGameOpts']();
}

export function GetGameReleases() {
  return window['go']['main']['App']['GetGameReleases']();
}

export function GetGameVersion() {
  return window['go']['main']['App']['GetGameVersion']();
}

export function GetGameVersionCheck() {
  return window['go']['main']['App']['GetGameVersionCheck']();
}

export function GetGpuPreference() {
  return window['go']['main']['App']['GetGpuPreference']();
}

export function GetInstallDir() {
  return window['go']['main']['App']['GetInstallDir']();
}

export function GetLauncherReleases() {
  return window['go']['main']['App']['GetLauncherReleases']();
}

export function GetLauncherVersion() {
  return window['go']['main']['App']['GetLauncherVersion']();
}

export function GetLauncherVersionCheck() {
  return window['go']['main']['App']['GetLauncherVersionCheck']();
}

export function IsGameRunning() {
  return window['go']['main']['App']['IsGameRunning']();
}

export function LaunchGame() {
  return window['go']['main']['App']['LaunchGame']();
}

export function MoveInstallDir(arg1) {
  return window['go']['main']['App']['MoveInstallDir'](arg1);
}

export function OpenInstallFolder() {
  return window['go']['main']['App']['OpenInstallFolder']();
}

export function RepairGame() {
  return window['go']['main']['App']['RepairGame']();
}

export function ResetGameOptsDefaults() {
  return window['go']['main']['App']['ResetGameOptsDefaults']();
}

export function ResetInstallPath() {
  return window['go']['main']['App']['ResetInstallPath']();
}

export function SelectInstallFolder() {
  return window['go']['main']['App']['SelectInstallFolder']();
}

export function SetGameOpt(arg1, arg2) {
  return window['go']['main']['App']['SetGameOpt'](arg1, arg2);
}

export function SetGpuPreference(arg1) {
  return window['go']['main']['App']['SetGpuPreference'](arg1);
}

export function StopGame() {
  return window['go']['main']['App']['StopGame']();
}

export function UninstallGame() {
  return window['go']['main']['App']['UninstallGame']();
}

export function UpdateLauncher() {
  return window['go']['main']['App']['UpdateLauncher']();
}
