// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DownloadGame():Promise<void>;

export function GetGPUs():Promise<Array<string>>;

export function GetGameOpts():Promise<Record<string, string>>;

export function GetGameReleases():Promise<Array<main.Release>>;

export function GetGameVersion():Promise<string>;

export function GetGameVersionCheck():Promise<main.GameVersionCheck>;

export function GetGpuPreference():Promise<boolean>;

export function GetInstallDir():Promise<string>;

export function GetLauncherReleases():Promise<Array<main.Release>>;

export function GetLauncherVersion():Promise<string>;

export function GetLauncherVersionCheck():Promise<main.LauncherVersionCheck>;

export function IsGameRunning():Promise<boolean>;

export function LaunchGame():Promise<void>;

export function MoveInstallDir(arg1:string):Promise<void>;

export function OpenInstallFolder():Promise<void>;

export function ResetGameOptsDefaults():Promise<Record<string, string>>;

export function SelectInstallFolder():Promise<string>;

export function SetGameOpt(arg1:string,arg2:string):Promise<void>;

export function SetGpuPreference(arg1:boolean):Promise<void>;

export function StopGame():Promise<void>;

export function UninstallGame():Promise<void>;

export function UpdateLauncher():Promise<void>;
